// SEED DATA — generated by scripts/generate-seed-data.ts on 2026-07-07.
// Real titles sourced from TMDB (image.tmdb.org) and Google Books APIs.
// Replace with live Supabase/TMDB/Google Books calls in Phase 4.
// Do NOT edit manually — re-run the script to refresh.
//
// TMDB attribution: "This app uses the TMDB API but is not endorsed or certified by TMDB."
// Poster images © The Movie Database (TMDB). Google Books data © Google LLC.

export type MediaType = 'film' | 'tv' | 'book';

/** Card data shape — mirrors what Phase 4 live API calls will return. */
export interface SeedCardItem {
  id:        string;
  title:     string;
  year:      number;
  mediaType: MediaType;
  /** TMDB CDN URL (image.tmdb.org/t/p/w342) or Google Books thumbnail. null = show fallback. */
  posterUrl: string | null;
  /** 2-3 dominant dark hex colors extracted from posterUrl by generate-seed-data.ts.
   *  Set only for atmosphere-relevant items (Daily Reel + Collection of the Week deck).
   *  Never computed at runtime — always static. */
  dominantColors?: string[];
}

/** Single dominant featured recommendation — extends SeedCardItem with editorial reason copy. */
export interface SeedFeaturedItem extends SeedCardItem {
  /** One editorial sentence explaining why this is recommended right now. Static for Phase 5. */
  reason: string;
}

export interface SeedContinueItem extends SeedCardItem {
  /** 0–1 viewing/reading progress */
  progress: number;
  subtitle: string;
}

/** Daily Reel pick — the signature recommendation; supersedes FeaturedToday. */
export interface SeedDailyReelItem extends SeedCardItem {
  /** Editorial body copy about the pick (1–2 sentences). */
  description: string;
  /** One-line "why ReelShelf picked this" tagline. */
  reason: string;
}

/** Book of the Week — book card with author and editorial description. */
export interface SeedBookItem extends SeedCardItem {
  author: string;
  /** Editorial body copy about the book (1–2 sentences). */
  description: string;
}

export interface SeedCollectionItem {
  id:          string;
  title:       string;
  /** Short editorial description (one line). */
  description: string;
  /** Representative story count for the full collection — editorial, not an exact count. */
  storyCount:  number;
  /** 3-4 preview items with poster + navigation metadata. null posterUrl shows a fallback tile. */
  items:       SeedCardItem[];
}

/** Award-winning film or show — extends SeedCardItem with a short award label. */
export interface SeedAwardItem extends SeedCardItem {
  /** Short award label, e.g. "Academy Award — Best Picture". */
  award: string;
}

// ── Featured Today (backward-compat) ─────────────────────────────────────────
export const featuredItem: SeedFeaturedItem = {
  "id": "film-872585",
  "title": "Oppenheimer",
  "year": 2023,
  "mediaType": "film",
  "posterUrl": "https://image.tmdb.org/t/p/w342/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
  "reason": "Nolan's three-hour reckoning with conscience and consequence — the kind of film that leaves you sitting in silence after the credits roll."
};

// ── Featured (kept for backward-compat — no longer rendered as a 3-card carousel) ──
export const featuredCards: SeedCardItem[] = [
  {
    "id": "film-872585",
    "title": "Oppenheimer",
    "year": 2023,
    "mediaType": "film",
    "posterUrl": "https://image.tmdb.org/t/p/w342/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg"
  },
  {
    "id": "tv-136315",
    "title": "The Bear",
    "year": 2022,
    "mediaType": "tv",
    "posterUrl": "https://image.tmdb.org/t/p/w342/eKfVzzEazSIjJMrw9ADa2x8ksLz.jpg"
  },
  {
    "id": "book-dune",
    "title": "Dune",
    "year": 1965,
    "mediaType": "book",
    "posterUrl": null
  }
];

// ── Trending Today ────────────────────────────────────────────────────────────
export const trendingToday: SeedCardItem[] = [
  {
    "id": "film-27205",
    "title": "Inception",
    "year": 2010,
    "mediaType": "film",
    "posterUrl": "https://image.tmdb.org/t/p/w342/xlaY2zyzMfkhk0HSC5VUwzoZPU1.jpg"
  },
  {
    "id": "film-693134",
    "title": "Dune: Part Two",
    "year": 2024,
    "mediaType": "film",
    "posterUrl": "https://image.tmdb.org/t/p/w342/heM4XKC0jA8fTSNe8F7oUkcJV7Z.jpg"
  },
  {
    "id": "tv-126308",
    "title": "Shōgun",
    "year": 2024,
    "mediaType": "tv",
    "posterUrl": "https://image.tmdb.org/t/p/w342/7O4iVfOMQmdCSxhOg1WnzG1AgYT.jpg"
  },
  {
    "id": "film-496243",
    "title": "Parasite",
    "year": 2019,
    "mediaType": "film",
    "posterUrl": "https://image.tmdb.org/t/p/w342/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg"
  },
  {
    "id": "film-792307",
    "title": "Poor Things",
    "year": 2023,
    "mediaType": "film",
    "posterUrl": "https://image.tmdb.org/t/p/w342/kCGlIMHnOm8JPXq3rXM6c5wMxcT.jpg"
  },
  {
    "id": "film-545611",
    "title": "Everything Everywhere All at Once",
    "year": 2022,
    "mediaType": "film",
    "posterUrl": "https://image.tmdb.org/t/p/w342/u68AjlvlutfEIcpmbYpKcdi09ut.jpg"
  },
  {
    "id": "tv-76331",
    "title": "Succession",
    "year": 2018,
    "mediaType": "tv",
    "posterUrl": "https://image.tmdb.org/t/p/w342/z0XiwdrCQ9yVIr4O0pxzaAYRxdW.jpg"
  }
];

// ── Continue Watching (static example — replace with user state in Phase 4) ──
export const continueWatching: SeedContinueItem = {
  "id": "continue-the-bear-s3",
  "title": "The Bear",
  "year": 2022,
  "mediaType": "tv",
  "posterUrl": "https://image.tmdb.org/t/p/w342/eKfVzzEazSIjJMrw9ADa2x8ksLz.jpg",
  "progress": 0.55,
  "subtitle": "Season 3 · Episode 1"
};

// ── Because You Loved (static example anchored to "Babylon") ─────────────────
// Anchor title and list become personalized in Phase 4.
export const becauseYouLoved: SeedCardItem[] = [
  {
    "id": "film-313369",
    "title": "La La Land",
    "year": 2016,
    "mediaType": "film",
    "posterUrl": "https://image.tmdb.org/t/p/w342/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg"
  },
  {
    "id": "film-244786",
    "title": "Whiplash",
    "year": 2014,
    "mediaType": "film",
    "posterUrl": "https://image.tmdb.org/t/p/w342/7fn624j5lj3xTme2SgiLCeuedmO.jpg"
  },
  {
    "id": "film-466272",
    "title": "Once Upon a Time... in Hollywood",
    "year": 2019,
    "mediaType": "film",
    "posterUrl": "https://image.tmdb.org/t/p/w342/8j58iEBw9pOXFD2L0nt0ZXeHviB.jpg"
  },
  {
    "id": "film-194662",
    "title": "Birdman or (The Unexpected Virtue of Ignorance)",
    "year": 2014,
    "mediaType": "film",
    "posterUrl": "https://image.tmdb.org/t/p/w342/rHUg2AuIuLSIYMYFgavVwqt1jtc.jpg"
  },
  {
    "id": "film-804095",
    "title": "The Fabelmans",
    "year": 2022,
    "mediaType": "film",
    "posterUrl": "https://image.tmdb.org/t/p/w342/h7llKkqkkJtJrTOaDLuVeUYDQ7I.jpg"
  },
  {
    "id": "book-pachinko",
    "title": "Pachinko",
    "year": 2017,
    "mediaType": "book",
    "posterUrl": null
  },
  {
    "id": "film-1018",
    "title": "Mulholland Drive",
    "year": 2001,
    "mediaType": "film",
    "posterUrl": "https://image.tmdb.org/t/p/w342/x7A59t6ySylr1L7aubOQEA480vM.jpg"
  }
];

// ── Sprint 3: additional interfaces and section data ─────────────────────────

export const dailyReelPick: SeedDailyReelItem = {
  "id": "film-872585",
  "title": "Oppenheimer",
  "year": 2023,
  "mediaType": "film",
  "posterUrl": "https://image.tmdb.org/t/p/w342/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
  "description": "Christopher Nolan reconstructs the invention of the atomic bomb with three-hour precision — intercutting past, present, and moral reckoning in a way only cinema can.",
  "reason": "A film that gets heavier the longer you sit with it.",
  "dominantColors": ["#261408", "#0c0c1e", "#1a1006"]
};

// ── Because You Loved: Babylon (naming alias for existing BYL group) ──────────
export const bylBabylon: SeedCardItem[] = becauseYouLoved;

// ── Because You Loved: Dune (epic worlds, slow-burn world-building) ───────────
export const bylDune: SeedCardItem[] = [
  {
    "id": "film-693134",
    "title": "Dune: Part Two",
    "year": 2024,
    "mediaType": "film",
    "posterUrl": "https://image.tmdb.org/t/p/w342/heM4XKC0jA8fTSNe8F7oUkcJV7Z.jpg"
  },
  {
    "id": "film-329865",
    "title": "Arrival",
    "year": 2016,
    "mediaType": "film",
    "posterUrl": "https://image.tmdb.org/t/p/w342/x2FJsf1ElAgr63Y3PNPtJrcmpoe.jpg"
  },
  {
    "id": "film-335984",
    "title": "Blade Runner 2049",
    "year": 2017,
    "mediaType": "film",
    "posterUrl": "https://image.tmdb.org/t/p/w342/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg"
  },
  {
    "id": "film-27205",
    "title": "Inception",
    "year": 2010,
    "mediaType": "film",
    "posterUrl": "https://image.tmdb.org/t/p/w342/xlaY2zyzMfkhk0HSC5VUwzoZPU1.jpg"
  },
  {
    "id": "film-62",
    "title": "2001: A Space Odyssey",
    "year": 1968,
    "mediaType": "film",
    "posterUrl": "https://image.tmdb.org/t/p/w342/ve72VxNqjGM69Uky4WTo2bK6rfq.jpg"
  }
];

// ── Because You Loved: The Bear (pressure, precision, people who care too much) ─
export const bylTheBear: SeedCardItem[] = [
  {
    "id": "tv-136315",
    "title": "The Bear",
    "year": 2022,
    "mediaType": "tv",
    "posterUrl": "https://image.tmdb.org/t/p/w342/eKfVzzEazSIjJMrw9ADa2x8ksLz.jpg"
  },
  {
    "id": "tv-76331",
    "title": "Succession",
    "year": 2018,
    "mediaType": "tv",
    "posterUrl": "https://image.tmdb.org/t/p/w342/z0XiwdrCQ9yVIr4O0pxzaAYRxdW.jpg"
  },
  {
    "id": "film-244786",
    "title": "Whiplash",
    "year": 2014,
    "mediaType": "film",
    "posterUrl": "https://image.tmdb.org/t/p/w342/7fn624j5lj3xTme2SgiLCeuedmO.jpg"
  },
  {
    "id": "film-194662",
    "title": "Birdman or (The Unexpected Virtue of Ignorance)",
    "year": 2014,
    "mediaType": "film",
    "posterUrl": "https://image.tmdb.org/t/p/w342/rHUg2AuIuLSIYMYFgavVwqt1jtc.jpg"
  },
  {
    "id": "film-593643",
    "title": "The Menu",
    "year": 2022,
    "mediaType": "film",
    "posterUrl": "https://image.tmdb.org/t/p/w342/fPtUgMcLIboqlTlPrq0bQpKK8eq.jpg"
  }
];

// ── Book of the Week ──────────────────────────────────────────────────────────
// posterUrl: null — extend with Google Books cover fetch in Phase 4.
export const bookOfTheWeek: SeedBookItem = {
  "id": "book-tomorrow-and-tomorrow",
  "title": "Tomorrow, and Tomorrow, and Tomorrow",
  "year": 2022,
  "mediaType": "book",
  "posterUrl": null,
  "author": "Gabrielle Zevin",
  "description": "Two friends spend thirty years building video games together — a novel about creation, obsession, and the invisible grammar of a long collaboration."
};

// ── Discover: Hidden Gems ────────────────────────────────────────────────────
// Curated lesser-known films. posterUrl = null items show letter fallback;
// run scripts/generate-seed-data.ts with EXPO_PUBLIC_TMDB_API_KEY to populate.
export const hiddenGems: SeedCardItem[] = [
  { id: "film-376867", title: "Moonlight",                 year: 2016, mediaType: "film", posterUrl: "https://image.tmdb.org/t/p/w342/qLnfEmPrDjJfPyyddLJPkXmshkp.jpg" },
  { id: "film-152601", title: "Her",                       year: 2013, mediaType: "film", posterUrl: "https://image.tmdb.org/t/p/w342/eCOtqtfvn7mxGl6nfmq4b1exJRc.jpg" },
  { id: "film-492188", title: "Marriage Story",            year: 2019, mediaType: "film", posterUrl: "https://image.tmdb.org/t/p/w342/2JRyCKaRKyJAVpsIHeLvPw5nHmw.jpg" },
  { id: "film-575264", title: "The Lighthouse",            year: 2019, mediaType: "film", posterUrl: null },
  { id: "film-435022", title: "The Florida Project",       year: 2017, mediaType: "film", posterUrl: null },
  { id: "film-344968", title: "Hunt for the Wilderpeople", year: 2016, mediaType: "film", posterUrl: null },
  { id: "film-418064", title: "A Ghost Story",             year: 2017, mediaType: "film", posterUrl: null },
];

// ── Discover: Random Discovery pool ──────────────────────────────────────────
// Static pool for the "I can't decide" shuffle card. Deduplicated union of
// curated lists. Items with posterUrl = null show the letter-fallback.
const _poolRaw: SeedCardItem[] = [
  // Trending
  { id: "film-27205",   title: "Inception",                         year: 2010, mediaType: "film", posterUrl: "https://image.tmdb.org/t/p/w342/xlaY2zyzMfkhk0HSC5VUwzoZPU1.jpg" },
  { id: "film-693134",  title: "Dune: Part Two",                    year: 2024, mediaType: "film", posterUrl: "https://image.tmdb.org/t/p/w342/heM4XKC0jA8fTSNe8F7oUkcJV7Z.jpg" },
  { id: "film-496243",  title: "Parasite",                          year: 2019, mediaType: "film", posterUrl: "https://image.tmdb.org/t/p/w342/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg" },
  { id: "film-792307",  title: "Poor Things",                       year: 2023, mediaType: "film", posterUrl: "https://image.tmdb.org/t/p/w342/kCGlIMHnOm8JPXq3rXM6c5wMxcT.jpg" },
  { id: "film-545611",  title: "Everything Everywhere All at Once", year: 2022, mediaType: "film", posterUrl: "https://image.tmdb.org/t/p/w342/u68AjlvlutfEIcpmbYpKcdi09ut.jpg" },
  // Arthouse / acclaimed
  { id: "film-376867",  title: "Moonlight",                         year: 2016, mediaType: "film", posterUrl: "https://image.tmdb.org/t/p/w342/qLnfEmPrDjJfPyyddLJPkXmshkp.jpg" },
  { id: "film-152601",  title: "Her",                               year: 2013, mediaType: "film", posterUrl: "https://image.tmdb.org/t/p/w342/eCOtqtfvn7mxGl6nfmq4b1exJRc.jpg" },
  { id: "film-492188",  title: "Marriage Story",                    year: 2019, mediaType: "film", posterUrl: "https://image.tmdb.org/t/p/w342/2JRyCKaRKyJAVpsIHeLvPw5nHmw.jpg" },
  { id: "film-329865",  title: "Arrival",                           year: 2016, mediaType: "film", posterUrl: "https://image.tmdb.org/t/p/w342/x2FJsf1ElAgr63Y3PNPtJrcmpoe.jpg" },
  { id: "film-335984",  title: "Blade Runner 2049",                 year: 2017, mediaType: "film", posterUrl: "https://image.tmdb.org/t/p/w342/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg" },
  // Horror / A24
  { id: "film-493922",  title: "Hereditary",                        year: 2018, mediaType: "film", posterUrl: "https://image.tmdb.org/t/p/w342/4GFPuL14eXi66V96xBWY73Y9PfR.jpg" },
  { id: "film-530385",  title: "Midsommar",                         year: 2019, mediaType: "film", posterUrl: "https://image.tmdb.org/t/p/w342/7LEI8ulZzO5gy9Ww2NVCrKmHeDZ.jpg" },
  { id: "film-419430",  title: "Get Out",                           year: 2017, mediaType: "film", posterUrl: "https://image.tmdb.org/t/p/w342/tFXcEccSQMf3lfhfXKSU9iRBpa3.jpg" },
  // Hidden gems (null poster = letter fallback)
  { id: "film-575264",  title: "The Lighthouse",                    year: 2019, mediaType: "film", posterUrl: null },
  { id: "film-435022",  title: "The Florida Project",               year: 2017, mediaType: "film", posterUrl: null },
];

// Deduplicate by id
const _seenIds = new Set<string>();
export const randomDiscoveryPool: SeedCardItem[] = _poolRaw.filter(item => {
  if (_seenIds.has(item.id)) return false;
  _seenIds.add(item.id);
  return true;
});

// ── Discover Phase 2: Award Winners ──────────────────────────────────────────
// Landscape-card section. award = short badge text shown on the card.
export const awardWinners: SeedAwardItem[] = [
  { id: "film-496243", title: "Parasite",            year: 2019, mediaType: "film", posterUrl: "https://image.tmdb.org/t/p/w342/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg", award: "Best Picture 2020" },
  { id: "film-376867", title: "Moonlight",           year: 2016, mediaType: "film", posterUrl: "https://image.tmdb.org/t/p/w342/qLnfEmPrDjJfPyyddLJPkXmshkp.jpg", award: "Best Picture 2017" },
  { id: "film-752623", title: "Nomadland",           year: 2020, mediaType: "film", posterUrl: "https://image.tmdb.org/t/p/w342/rnheO8cFvCYcmZsDrBoabJbKLFE.jpg", award: "Best Picture 2021" },
  { id: "film-313369", title: "La La Land",          year: 2016, mediaType: "film", posterUrl: "https://image.tmdb.org/t/p/w342/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg", award: "Golden Globe — Best Picture" },
  { id: "film-244786", title: "Whiplash",            year: 2014, mediaType: "film", posterUrl: "https://image.tmdb.org/t/p/w342/7fn624j5lj3xTme2SgiLCeuedmO.jpg", award: "Academy Award — Film Editing" },
  { id: "film-399055", title: "The Shape of Water",  year: 2017, mediaType: "film", posterUrl: null,                                                                  award: "Best Picture 2018" },
  { id: "tv-76331",    title: "Succession",          year: 2018, mediaType: "tv",   posterUrl: "https://image.tmdb.org/t/p/w342/z0XiwdrCQ9yVIr4O0pxzaAYRxdW.jpg", award: "Emmy — Outstanding Drama" },
  { id: "tv-87108",    title: "Chernobyl",           year: 2019, mediaType: "tv",   posterUrl: null,                                                                  award: "Emmy — Limited Series 2019" },
];

// ── Discover Phase 2: Mind-Bending films (stacked-shadow section) ─────────────
// Single-item stacked-shadow cards — distinct from c-mindbend/c-mindbend2 collections.
// Uses c-mindbend's title pool + mulholland for variety.
export const mindBendingFilms: SeedCardItem[] = [
  { id: "film-27205",  title: "Inception",          year: 2010, mediaType: "film", posterUrl: "https://image.tmdb.org/t/p/w342/xlaY2zyzMfkhk0HSC5VUwzoZPU1.jpg" },
  { id: "film-329865", title: "Arrival",             year: 2016, mediaType: "film", posterUrl: "https://image.tmdb.org/t/p/w342/x2FJsf1ElAgr63Y3PNPtJrcmpoe.jpg" },
  { id: "film-335984", title: "Blade Runner 2049",   year: 2017, mediaType: "film", posterUrl: "https://image.tmdb.org/t/p/w342/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg" },
  { id: "film-550",    title: "Fight Club",          year: 1999, mediaType: "film", posterUrl: "https://image.tmdb.org/t/p/w342/jSziioSwPVrOy9Yow3XhWIBDjq1.jpg" },
  { id: "film-1018",   title: "Mulholland Drive",    year: 2001, mediaType: "film", posterUrl: "https://image.tmdb.org/t/p/w342/x7A59t6ySylr1L7aubOQEA480vM.jpg" },
  { id: "film-496243", title: "Parasite",            year: 2019, mediaType: "film", posterUrl: "https://image.tmdb.org/t/p/w342/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg" },
];

// ── Discover Phase 2: TV Picks ────────────────────────────────────────────────
// Large landscape cards, Apple TV style (portrait poster fills a landscape frame).
export const tvPicks: SeedCardItem[] = [
  { id: "tv-136315", title: "The Bear",       year: 2022, mediaType: "tv", posterUrl: "https://image.tmdb.org/t/p/w342/eKfVzzEazSIjJMrw9ADa2x8ksLz.jpg" },
  { id: "tv-76331",  title: "Succession",     year: 2018, mediaType: "tv", posterUrl: "https://image.tmdb.org/t/p/w342/z0XiwdrCQ9yVIr4O0pxzaAYRxdW.jpg" },
  { id: "tv-126308", title: "Shōgun",         year: 2024, mediaType: "tv", posterUrl: "https://image.tmdb.org/t/p/w342/7O4iVfOMQmdCSxhOg1WnzG1AgYT.jpg" },
  { id: "tv-87108",  title: "Chernobyl",      year: 2019, mediaType: "tv", posterUrl: null },
  { id: "tv-95396",  title: "Severance",      year: 2022, mediaType: "tv", posterUrl: null },
  { id: "tv-100088", title: "The Last of Us", year: 2023, mediaType: "tv", posterUrl: null },
];

// ── Discover Phase 2: Book Section ───────────────────────────────────────────
// Three sub-groups. posterUrl = null → gradient letter-fallback (books don't
// have consistent CDN URLs; re-run generate-seed-data.ts to populate via Google Books).

export const bookOfTheMonth: SeedBookItem = {
  id:          "book-remains-of-the-day",
  title:       "The Remains of the Day",
  year:         1989,
  mediaType:   "book",
  posterUrl:   null,
  author:      "Kazuo Ishiguro",
  description: "A butler's quiet reflections on duty and suppressed feeling reveal the cost of a life given entirely to service — Ishiguro's Booker Prize masterpiece of restraint.",
};

export const trendingBooks: SeedBookItem[] = [
  { id: "book-normal-people",      title: "Normal People",          year: 2018, mediaType: "book", posterUrl: null, author: "Sally Rooney",        description: "Two Irish students drift together and apart over several years — a precise study of how love and class shape the people we become." },
  { id: "book-midnight-library",   title: "The Midnight Library",   year: 2020, mediaType: "book", posterUrl: null, author: "Matt Haig",           description: "A library between life and death holds every book of every life you could have lived — a moving meditation on regret and possibility." },
  { id: "book-a-little-life",      title: "A Little Life",          year: 2015, mediaType: "book", posterUrl: null, author: "Hanya Yanagihara",    description: "Four friends navigate adulthood in New York across three decades — an unsparing, devastating novel about trauma, love, and survival." },
  { id: "book-fourth-wing",        title: "Fourth Wing",            year: 2023, mediaType: "book", posterUrl: null, author: "Rebecca Yarros",      description: "A war college for dragon riders, a heroine who shouldn't be there, and a rebellion building in the shadows — ferociously entertaining." },
  { id: "book-demon-copperhead",   title: "Demon Copperhead",       year: 2022, mediaType: "book", posterUrl: null, author: "Barbara Kingsolver",  description: "A Pulitzer Prize-winning retelling of David Copperfield set in the opioid-ravaged Appalachian Mountains — Dickens as American tragedy." },
];

export const awardWinnerBooks: SeedBookItem[] = [
  { id: "book-the-road",            title: "The Road",                  year: 2006, mediaType: "book", posterUrl: null, author: "Cormac McCarthy",   description: "A father and son cross a devastated American landscape — McCarthy's Pulitzer-winning novel distils love and survival to their barest elements." },
  { id: "book-lincoln-bardo",       title: "Lincoln in the Bardo",      year: 2017, mediaType: "book", posterUrl: null, author: "George Saunders",   description: "Abraham Lincoln visits his son's tomb; the dead speak. A Booker Prize-winning novel unlike anything else — grief rendered as polyphony." },
  { id: "book-underground-railroad", title: "The Underground Railroad",  year: 2016, mediaType: "book", posterUrl: null, author: "Colson Whitehead",  description: "A Pulitzer Prize-winning reimagining of the Underground Railroad as a literal network of secret trains carrying enslaved people to freedom." },
  { id: "book-gentleman-moscow",    title: "A Gentleman in Moscow",     year: 2016, mediaType: "book", posterUrl: null, author: "Amor Towles",       description: "A count sentenced to house arrest in a luxury Moscow hotel finds that even a world reduced to one building can contain an entire life." },
];

// discoverCollections (Discover's Additional Collections row) has been
// removed — CollectionsRow now reads real live collections via
// lib/supabase/collections.ts's fetchAdditionalCollections().
