// SEED DATA — generated by scripts/generate-seed-data.ts on 2026-07-06.
// Real titles sourced from TMDB (image.tmdb.org) and Google Books APIs.
// Replace with live Supabase/TMDB/Google Books calls in Phase 4.
// Do NOT edit manually — re-run the script to refresh.
//
// TMDB attribution: "This app uses the TMDB API but is not endorsed or certified by TMDB."
// Poster images © The Movie Database (TMDB). Google Books data © Google LLC.

export type MediaType = 'film' | 'tv' | 'book';

/** Card data shape — mirrors what Phase 4 live API calls will return. */
export interface SeedCardItem {
  id:        string;
  title:     string;
  year:      number;
  mediaType: MediaType;
  /** TMDB CDN URL (image.tmdb.org/t/p/w342) or Google Books thumbnail. null = show fallback. */
  posterUrl: string | null;
}

/** Single dominant featured recommendation — extends SeedCardItem with editorial reason copy. */
export interface SeedFeaturedItem extends SeedCardItem {
  /** One editorial sentence explaining why this is recommended right now. Static for Phase 5. */
  reason: string;
}

export interface SeedContinueItem extends SeedCardItem {
  /** 0–1 viewing/reading progress */
  progress: number;
  subtitle: string;
}

export interface SeedCollectionItem {
  id:       string;
  title:    string;
  subtitle: string;
  coverUrl: string | null;
}

// ── Featured Today — single dominant recommendation ────────────────────────
// The ONE film/TV/book the app surfaces as today's confident pick.
// `reason` is the only field added this sprint (Phase 5 constraint).
export const featuredItem: SeedFeaturedItem = {
  id:        'film-872585',
  title:     'Oppenheimer',
  year:       2023,
  mediaType: 'film',
  posterUrl: 'https://image.tmdb.org/t/p/w342/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
  reason:    "Nolan's three-hour reckoning with conscience and consequence — the kind of film that leaves you sitting in silence after the credits roll.",
};

// ── Featured (kept for backward-compat — no longer rendered as a 3-card carousel) ──
export const featuredCards: SeedCardItem[] = [
  {
    "id": "film-872585",
    "title": "Oppenheimer",
    "year": 2023,
    "mediaType": "film",
    "posterUrl": "https://image.tmdb.org/t/p/w342/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg"
  },
  {
    "id": "tv-136315",
    "title": "The Bear",
    "year": 2022,
    "mediaType": "tv",
    "posterUrl": "https://image.tmdb.org/t/p/w342/eKfVzzEazSIjJMrw9ADa2x8ksLz.jpg"
  },
  {
    "id": "book-dune",
    "title": "Dune",
    "year": 1965,
    "mediaType": "book",
    "posterUrl": null
  }
];

// ── Trending Today ────────────────────────────────────────────────────────────
export const trendingToday: SeedCardItem[] = [
  {
    "id": "film-27205",
    "title": "Inception",
    "year": 2010,
    "mediaType": "film",
    "posterUrl": "https://image.tmdb.org/t/p/w342/xlaY2zyzMfkhk0HSC5VUwzoZPU1.jpg"
  },
  {
    "id": "film-693134",
    "title": "Dune: Part Two",
    "year": 2024,
    "mediaType": "film",
    "posterUrl": "https://image.tmdb.org/t/p/w342/heM4XKC0jA8fTSNe8F7oUkcJV7Z.jpg"
  },
  {
    "id": "tv-126308",
    "title": "Shōgun",
    "year": 2024,
    "mediaType": "tv",
    "posterUrl": "https://image.tmdb.org/t/p/w342/7O4iVfOMQmdCSxhOg1WnzG1AgYT.jpg"
  },
  {
    "id": "film-496243",
    "title": "Parasite",
    "year": 2019,
    "mediaType": "film",
    "posterUrl": "https://image.tmdb.org/t/p/w342/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg"
  },
  {
    "id": "film-792307",
    "title": "Poor Things",
    "year": 2023,
    "mediaType": "film",
    "posterUrl": "https://image.tmdb.org/t/p/w342/kCGlIMHnOm8JPXq3rXM6c5wMxcT.jpg"
  },
  {
    "id": "film-545611",
    "title": "Everything Everywhere All at Once",
    "year": 2022,
    "mediaType": "film",
    "posterUrl": "https://image.tmdb.org/t/p/w342/u68AjlvlutfEIcpmbYpKcdi09ut.jpg"
  },
  {
    "id": "tv-76331",
    "title": "Succession",
    "year": 2018,
    "mediaType": "tv",
    "posterUrl": "https://image.tmdb.org/t/p/w342/z0XiwdrCQ9yVIr4O0pxzaAYRxdW.jpg"
  }
];

// ── Continue Watching (static example — replace with user state in Phase 4) ──
export const continueWatching: SeedContinueItem = {
  "id": "continue-the-bear-s3",
  "title": "The Bear",
  "year": 2022,
  "mediaType": "tv",
  "posterUrl": "https://image.tmdb.org/t/p/w342/eKfVzzEazSIjJMrw9ADa2x8ksLz.jpg",
  "progress": 0.55,
  "subtitle": "Season 3 · Episode 1"
};

// ── Because You Loved (static example anchored to "Babylon") ─────────────────
// Anchor title and list become personalized in Phase 4.
export const becauseYouLoved: SeedCardItem[] = [
  {
    "id": "film-313369",
    "title": "La La Land",
    "year": 2016,
    "mediaType": "film",
    "posterUrl": "https://image.tmdb.org/t/p/w342/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg"
  },
  {
    "id": "film-244786",
    "title": "Whiplash",
    "year": 2014,
    "mediaType": "film",
    "posterUrl": "https://image.tmdb.org/t/p/w342/7fn624j5lj3xTme2SgiLCeuedmO.jpg"
  },
  {
    "id": "film-466272",
    "title": "Once Upon a Time... in Hollywood",
    "year": 2019,
    "mediaType": "film",
    "posterUrl": "https://image.tmdb.org/t/p/w342/8j58iEBw9pOXFD2L0nt0ZXeHviB.jpg"
  },
  {
    "id": "film-194662",
    "title": "Birdman or (The Unexpected Virtue of Ignorance)",
    "year": 2014,
    "mediaType": "film",
    "posterUrl": "https://image.tmdb.org/t/p/w342/rHUg2AuIuLSIYMYFgavVwqt1jtc.jpg"
  },
  {
    "id": "film-804095",
    "title": "The Fabelmans",
    "year": 2022,
    "mediaType": "film",
    "posterUrl": "https://image.tmdb.org/t/p/w342/h7llKkqkkJtJrTOaDLuVeUYDQ7I.jpg"
  },
  {
    "id": "book-pachinko",
    "title": "Pachinko",
    "year": 2017,
    "mediaType": "book",
    "posterUrl": null
  },
  {
    "id": "film-1018",
    "title": "Mulholland Drive",
    "year": 2001,
    "mediaType": "film",
    "posterUrl": "https://image.tmdb.org/t/p/w342/x7A59t6ySylr1L7aubOQEA480vM.jpg"
  }
];

// ── Sprint 3: additional interfaces and section data ─────────────────────────
// Manually curated. Run generate-seed-data.ts (with Google Books extension for
// bookOfTheWeek) to refresh poster/cover URLs from live APIs.

/** Daily Reel pick — the signature recommendation; supersedes FeaturedToday. */
export interface SeedDailyReelItem extends SeedCardItem {
  /** Editorial body copy about the pick (1–2 sentences). */
  description: string;
  /** One-line "why ReelShelf picked this" tagline. */
  reason: string;
}

/** Book of the Week — book card with author and editorial description. */
export interface SeedBookItem extends SeedCardItem {
  author: string;
  /** Editorial body copy about the book (1–2 sentences). */
  description: string;
}

export const dailyReelPick: SeedDailyReelItem = {
  id:          'film-872585',
  title:       'Oppenheimer',
  year:         2023,
  mediaType:   'film',
  posterUrl:   'https://image.tmdb.org/t/p/w342/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
  description: 'Christopher Nolan reconstructs the invention of the atomic bomb with three-hour precision — intercutting past, present, and moral reckoning in a way only cinema can.',
  reason:      'A film that gets heavier the longer you sit with it.',
};

// ── Because You Loved: Babylon (naming alias for existing BYL group) ──────────
export const bylBabylon: SeedCardItem[] = becauseYouLoved;

// ── Because You Loved: Dune (epic worlds, slow-burn world-building) ───────────
export const bylDune: SeedCardItem[] = [
  {
    id:        'film-693134',
    title:     'Dune: Part Two',
    year:       2024,
    mediaType: 'film',
    posterUrl: 'https://image.tmdb.org/t/p/w342/heM4XKC0jA8fTSNe8F7oUkcJV7Z.jpg',
  },
  {
    id:        'film-329865',
    title:     'Arrival',
    year:       2016,
    mediaType: 'film',
    posterUrl: 'https://image.tmdb.org/t/p/w342/x2FJsf1ElAgr63Y3PNPtJrcmpoe.jpg',
  },
  {
    id:        'film-335984',
    title:     'Blade Runner 2049',
    year:       2017,
    mediaType: 'film',
    posterUrl: 'https://image.tmdb.org/t/p/w342/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg',
  },
  {
    id:        'film-27205',
    title:     'Inception',
    year:       2010,
    mediaType: 'film',
    posterUrl: 'https://image.tmdb.org/t/p/w342/xlaY2zyzMfkhk0HSC5VUwzoZPU1.jpg',
  },
  {
    id:        'film-62',
    title:     '2001: A Space Odyssey',
    year:       1968,
    mediaType: 'film',
    posterUrl: 'https://image.tmdb.org/t/p/w342/re3DNYMBpH9kf0blNJqgb3CpaqE.jpg',
  },
];

// ── Because You Loved: The Bear (pressure, precision, people who care too much) ─
export const bylTheBear: SeedCardItem[] = [
  {
    id:        'tv-136315',
    title:     'The Bear',
    year:       2022,
    mediaType: 'tv',
    posterUrl: 'https://image.tmdb.org/t/p/w342/eKfVzzEazSIjJMrw9ADa2x8ksLz.jpg',
  },
  {
    id:        'tv-76331',
    title:     'Succession',
    year:       2018,
    mediaType: 'tv',
    posterUrl: 'https://image.tmdb.org/t/p/w342/z0XiwdrCQ9yVIr4O0pxzaAYRxdW.jpg',
  },
  {
    id:        'film-244786',
    title:     'Whiplash',
    year:       2014,
    mediaType: 'film',
    posterUrl: 'https://image.tmdb.org/t/p/w342/7fn624j5lj3xTme2SgiLCeuedmO.jpg',
  },
  {
    id:        'film-194662',
    title:     'Birdman',
    year:       2014,
    mediaType: 'film',
    posterUrl: 'https://image.tmdb.org/t/p/w342/rHUg2AuIuLSIYMYFgavVwqt1jtc.jpg',
  },
  {
    id:        'film-593643',
    title:     'The Menu',
    year:       2022,
    mediaType: 'film',
    posterUrl: null,
  },
];

// ── Book of the Week ──────────────────────────────────────────────────────────
// posterUrl: run generate-seed-data.ts (extend with Google Books fetch) to populate.
export const bookOfTheWeek: SeedBookItem = {
  id:          'book-tomorrow-and-tomorrow',
  title:       'Tomorrow, and Tomorrow, and Tomorrow',
  year:         2022,
  mediaType:   'book',
  posterUrl:   null,
  author:      'Gabrielle Zevin',
  description: 'Two friends spend thirty years building video games together — a novel about creation, obsession, and the invisible grammar of a long collaboration.',
};

// ── Collections ───────────────────────────────────────────────────────────────
export const collections: SeedCollectionItem[] = [
  {
    "id": "c-a24",
    "title": "Best A24 Films",
    "subtitle": "Fearless cinema from A24.",
    "coverUrl": "https://image.tmdb.org/t/p/w342/kCGlIMHnOm8JPXq3rXM6c5wMxcT.jpg"
  },
  {
    "id": "c-mindbend",
    "title": "Mind-Bending Stories",
    "subtitle": "Reality is just a suggestion.",
    "coverUrl": "https://image.tmdb.org/t/p/w342/xlaY2zyzMfkhk0HSC5VUwzoZPU1.jpg"
  },
  {
    "id": "c-sunday",
    "title": "Perfect Sunday Stories",
    "subtitle": "Slow, warm, unmissable.",
    "coverUrl": "https://image.tmdb.org/t/p/w342/u68AjlvlutfEIcpmbYpKcdi09ut.jpg"
  }
];
