import type { BadgeDefinition } from '@/types/badges';

// Complete catalog — `id` matches the `slug` field in the `badges` DB table.
// Legacy/Hidden entries have no `maxProgress` or `statKey`; unlock state must come
// exclusively from the `user_badges` join table, never from dynamic stats.
export const REELSHELF_BADGES: BadgeDefinition[] = [

  // ── Legacy ──────────────────────────────────────────────────────────────────
  {
    id: 'founding_member',
    name: 'Founding Member',
    description: 'Here from the absolute beginning.',
    unlockConditionText: 'Awarded to early alpha access accounts',
    category: 'Legacy',
    rarity: 'Legendary',
  },
  {
    id: 'beta_tester',
    name: 'Beta Legend',
    description: 'Helped shape ReelShelf through the beta phase.',
    unlockConditionText: 'Awarded to version 1.0 beta testing accounts',
    category: 'Legacy',
    rarity: 'Epic',
  },

  // ── Logging (films) ──────────────────────────────────────────────────────────
  {
    id: 'first_screening',
    name: 'First Screening',
    description: 'Every cinematic journey starts with one.',
    unlockConditionText: 'Log your first film',
    category: 'Logging',
    rarity: 'Common',
    maxProgress: 1,
    statKey: 'filmCount',
  },
  {
    id: 'film_enthusiast',
    name: 'Film Enthusiast',
    description: 'Stepping into the silver screen.',
    unlockConditionText: 'Log 10 films',
    category: 'Logging',
    rarity: 'Common',
    maxProgress: 10,
    statKey: 'filmCount',
  },
  {
    id: 'film_centennial',
    name: 'Film Centennial',
    description: 'A hundred stories told through light and shadow.',
    unlockConditionText: 'Log 100 films',
    category: 'Logging',
    rarity: 'Rare',
    maxProgress: 100,
    statKey: 'filmCount',
  },
  {
    id: 'marathon_viewer',
    name: 'Marathon Viewer',
    description: 'You have seen more films than most will in a lifetime.',
    unlockConditionText: 'Log 500 films',
    category: 'Logging',
    rarity: 'Epic',
    maxProgress: 500,
    statKey: 'filmCount',
  },

  // ── Logging (cinema visits) ───────────────────────────────────────────────────
  {
    id: 'cinema_debut',
    name: 'Cinema Debut',
    description: 'Nothing compares to the big screen.',
    unlockConditionText: 'Log your first cinema visit',
    category: 'Logging',
    rarity: 'Common',
    maxProgress: 1,
    statKey: 'cinemaCount',
  },
  {
    id: 'cinema_regular',
    name: 'Cinema Regular',
    description: 'The usher knows your face.',
    unlockConditionText: 'Log 5 cinema visits',
    category: 'Logging',
    rarity: 'Common',
    maxProgress: 5,
    statKey: 'cinemaCount',
  },
  {
    id: 'imax_enthusiast',
    name: 'IMAX Enthusiast',
    description: 'Bigger, louder, better.',
    unlockConditionText: 'Log 10 cinema visits',
    category: 'Logging',
    rarity: 'Rare',
    maxProgress: 10,
    statKey: 'cinemaCount',
  },
  {
    id: 'silver_screen',
    name: 'Silver Screen',
    description: 'The cinema is your second home.',
    unlockConditionText: 'Log 25 cinema visits',
    category: 'Logging',
    rarity: 'Epic',
    maxProgress: 25,
    statKey: 'cinemaCount',
  },

  // ── Logging (streaks) ─────────────────────────────────────────────────────────
  {
    id: 'week_streak',
    name: 'Week Streak',
    description: 'Seven days of consistent logging.',
    unlockConditionText: 'Maintain a 7-day logging streak',
    category: 'Logging',
    rarity: 'Common',
    maxProgress: 7,
    statKey: 'longestStreak',
  },
  {
    id: 'month_streak',
    name: 'Month Streak',
    description: 'Thirty days without breaking the chain.',
    unlockConditionText: 'Maintain a 30-day logging streak',
    category: 'Logging',
    rarity: 'Rare',
    maxProgress: 30,
    statKey: 'longestStreak',
  },
  {
    id: 'shelf_discipline',
    name: 'Shelf Discipline',
    description: 'A hundred consecutive days. Iron will.',
    unlockConditionText: 'Maintain a 100-day logging streak',
    category: 'Logging',
    rarity: 'Epic',
    maxProgress: 100,
    statKey: 'longestStreak',
  },
  {
    id: 'unstoppable',
    name: 'Unstoppable',
    description: 'A full year of logging. Legendary.',
    unlockConditionText: 'Maintain a 365-day logging streak',
    category: 'Logging',
    rarity: 'Legendary',
    maxProgress: 365,
    statKey: 'longestStreak',
  },

  // ── Logging (prestige meta-achievements) ─────────────────────────────────────
  {
    id: 'completionist',
    name: 'Completionist',
    description: 'Ten badges earned. The collection grows.',
    unlockConditionText: 'Earn 10 badges',
    category: 'Logging',
    rarity: 'Rare',
    maxProgress: 10,
  },
  {
    id: 'reelshelf_scholar',
    name: 'ReelShelf Scholar',
    description: 'Twenty badges. Your passion is undeniable.',
    unlockConditionText: 'Earn 20 badges',
    category: 'Logging',
    rarity: 'Epic',
    maxProgress: 20,
  },

  // ── TV ────────────────────────────────────────────────────────────────────────
  {
    id: 'pilot_episode',
    name: 'Pilot Episode',
    description: 'Your streaming journey begins.',
    unlockConditionText: 'Log your first TV show',
    category: 'TV',
    rarity: 'Common',
    maxProgress: 1,
    statKey: 'tvCount',
  },
  {
    id: 'binge_mode',
    name: 'Binge Mode',
    description: 'Mastered the remote control.',
    unlockConditionText: 'Log 10 TV shows',
    category: 'TV',
    rarity: 'Common',
    maxProgress: 10,
    statKey: 'tvCount',
  },
  {
    id: 'sitcom_survivor',
    name: 'Sitcom Survivor',
    description: 'Outlasted more cliffhangers than most could handle.',
    unlockConditionText: 'Log 25 TV shows',
    category: 'TV',
    rarity: 'Rare',
    maxProgress: 25,
    statKey: 'tvCount',
  },
  {
    id: 'prestige_television',
    name: 'Prestige Television',
    description: 'A connoisseur of the small-screen golden age.',
    unlockConditionText: 'Log 50 TV shows',
    category: 'TV',
    rarity: 'Epic',
    maxProgress: 50,
    statKey: 'tvCount',
  },

  // ── Books ────────────────────────────────────────────────────────────────────
  {
    id: 'page_turner',
    name: 'Page Turner',
    description: 'Words worth keeping.',
    unlockConditionText: 'Log your first book',
    category: 'Books',
    rarity: 'Common',
    maxProgress: 1,
    statKey: 'bookCount',
  },
  {
    id: 'bookworm',
    name: 'Bookworm',
    description: 'Reading more than your eyebrows can handle.',
    unlockConditionText: 'Log 20 books',
    category: 'Books',
    rarity: 'Rare',
    maxProgress: 20,
    statKey: 'bookCount',
  },
  {
    id: 'literary_taste',
    name: 'Literary Taste',
    description: 'Fifty books — your shelf speaks for itself.',
    unlockConditionText: 'Log 50 books',
    category: 'Books',
    rarity: 'Epic',
    maxProgress: 50,
    statKey: 'bookCount',
  },

  // ── Reviews ──────────────────────────────────────────────────────────────────
  {
    id: 'first_review',
    name: 'First Review',
    description: 'Putting your thoughts into the world.',
    unlockConditionText: 'Write your first review',
    category: 'Reviews',
    rarity: 'Common',
    maxProgress: 1,
    statKey: 'reviewCount',
  },
  {
    id: 'critic_in_training',
    name: 'Critic in Training',
    description: 'The pen is sharper than any lens.',
    unlockConditionText: 'Write 10 reviews',
    category: 'Reviews',
    rarity: 'Rare',
    maxProgress: 10,
    statKey: 'reviewCount',
  },
  {
    id: 'cultural_commentator',
    name: 'Cultural Commentator',
    description: 'Fifty takes worth reading.',
    unlockConditionText: 'Write 50 reviews',
    category: 'Reviews',
    rarity: 'Epic',
    maxProgress: 50,
    statKey: 'reviewCount',
  },
  {
    id: 'master_critic',
    name: 'Master Critic',
    description: 'A hundred reviews. Your voice is unmistakable.',
    unlockConditionText: 'Write 100 reviews',
    category: 'Reviews',
    rarity: 'Legendary',
    maxProgress: 100,
    statKey: 'reviewCount',
  },

  // ── Social ───────────────────────────────────────────────────────────────────
  {
    id: 'first_follower',
    name: 'First Follower',
    description: 'Someone believes in your taste.',
    unlockConditionText: 'Gain your first follower',
    category: 'Social',
    rarity: 'Common',
    maxProgress: 1,
    statKey: 'followersCount',
  },
  {
    id: 'social_butterfly',
    name: 'Social Butterfly',
    description: 'Your recommendations carry weight.',
    unlockConditionText: 'Gain 10 followers',
    category: 'Social',
    rarity: 'Rare',
    maxProgress: 10,
    statKey: 'followersCount',
  },
  {
    id: 'conversation_starter',
    name: 'Conversation Starter',
    description: 'Someone had something to say about your take.',
    unlockConditionText: 'Receive your first comment',
    category: 'Social',
    rarity: 'Common',
    maxProgress: 1,
    statKey: 'commentsReceived',
  },
  {
    id: 'critics_circle',
    name: "Critics' Circle",
    description: 'Fifty people found your reviews worth liking.',
    unlockConditionText: 'Receive 50 likes on your reviews',
    category: 'Social',
    rarity: 'Epic',
    maxProgress: 50,
    statKey: 'likesReceived',
  },

  // ── Hidden (manually awarded / secret — no statKey, DB-only unlock) ──────────
  {
    id: 'criterion_minded',
    name: 'Criterion Minded',
    description: 'A deep reverence for the canon.',
    unlockConditionText: 'Manually awarded — curated taste recognition',
    category: 'Hidden',
    rarity: 'Rare',
  },
  {
    id: 'nolan_archivist',
    name: 'Nolan Archivist',
    description: 'Every frame of every timeline, catalogued.',
    unlockConditionText: 'Manually awarded — Nolan completionist',
    category: 'Hidden',
    rarity: 'Epic',
  },
  {
    id: 'sci_fi_scholar',
    name: 'Sci-Fi Scholar',
    description: 'Building a library of imagined futures.',
    unlockConditionText: 'Manually awarded — science fiction enthusiast',
    category: 'Hidden',
    rarity: 'Rare',
  },
];
